Use EMR 5.2.0 which is built on Spark 2.0.2.
On EMR 4.7.2 I got this error:

```
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:379) ~[hadoop-mapreduce-client-core-2.6.4.jar:na]
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:121) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.8.jar:na]
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:246) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.8.jar:na]
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:246) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at scala.Option.getOrElse(Option.scala:121) [org.scala-lang.scala-library-2.11.8.jar:na]
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:246) ~[spark-core_2.11-2.0.2.jar:2.0.2]
	at com.lynxanalytics.biggraph.spark_util.Implicits$PairRDDUtils.asUniqueSortedRDD(RDDUtils.scala:390) ~[biggraph.biggraph-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
```

I am surprised to see Hadoop 2.6.4 on the stack trace. EMR 4.7.0 is supposed to have Hadoop 2.7.2.
And I was able to run a big data test earlier without issues. Anyway, it cannot hurt.